SET SERVEROUTPUT ON;
ALTER SESSION SET NLS_LANGUAGE = 'FRENCH';
DECLARE
v_todayhour VARCHAR2(50);
BEGIN
SELECT to_char(SYSDATE,'HH24 MI SS') INTO v_todayhour FROM DUAL;
DBMS_OUTPUT.PUT_LINE('Il est ' || v_todayhour);
END;