--/***************************************************************
--Script req_delice_TODO.sql
--***************************************************************/
-- On interprete  les &  comme variable de substitution
set define on

-- affichage des substitutions de variable
set verify on

--2.1.1
SELECT * FROM ARTICLE;
SELECT * FROM CLIENT;
SELECT * FROM COMMANDE;
SELECT * FROM DETAILLIVRAISON;
SELECT * FROM LIGNECOMMANDE;
SELECT * FROM LIVRAISON;

-- 2.1.2
SELECT * FROM CLIENT WHERE NOTELEPHONE = '(999)999-9999';

-- 2.2.1
SELECT C.NOCOMMANDE, SUM(PRIXUNITAIRE*QUANTITE) AS Total, SUM(PRIXUNITAIRE*QUANTITE)*1.15 AS "Total avec taxe" FROM COMMANDE C 
    INNER JOIN LIGNECOMMANDE LC ON C.NOCOMMANDE = LC.NOCOMMANDE 
    INNER JOIN ARTICLE A ON LC.NOARTICLE = A.NOARTICLE
    WHERE C.NOCOMMANDE = 1
    GROUP BY C.NOCOMMANDE;
    
-- 2.3.1
DELETE FROM ARTICLE WHERE ARTICLE.NOARTICLE NOT IN (SELECT NOARTICLE FROM LIGNECOMMANDE);
rollback;

-- 2.4.1
SELECT CL.NOCLIENT, CL.NOTELEPHONE, CO.NOCOMMANDE FROM CLIENT CL
    INNER JOIN COMMANDE CO ON CL.NOCLIENT = CO.NOCLIENT
    WHERE TO_DATE(CO.DATECOMMANDE) = TO_DATE('02/06/2000','DD/MM/YYYY');

-- 2.5.1
SELECT LIV.noLivraison FROM LIVRAISON LIV
    INNER JOIN DETAILLIVRAISON DLIV ON LIV.NOLIVRAISON = DLIV.NOLIVRAISON
    WHERE TO_DATE(LIV.DATELIVRAISON) = TO_DATE('04/06/2000','DD/MM/YYYY')
    GROUP BY LIV.NOLIVRAISON
    HAVING COUNT(DLIV.NOLIVRAISON)>= 2
    ORDER BY LIV.NOLIVRAISON ASC;
