-- Redirection de la sortie
set define off
SPOOL cdu.log
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('000' ,'Généralités sur l’informatique, l’information, ouvrages généraux');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('001' ,'Connaissance');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('002' ,'Livre (écrits, bibliothèques, et sujets en rapport aux livres)');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('003' ,'Systèmes');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('004' ,'Traitement de données et Informatique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('005' ,'Programmation informatique, Logiciels et donnée');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('006' ,'Applications informatique');

INSERT INTO THEME (noTheme,intituleTheme) VALUES ('010' ,'Bibliographie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('011' ,'Bibliographies');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('012' ,'Bibliographies d''individus');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('013' ,'(Vacant)');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('014' ,'Bibliographies d''ouvrages anonymes ou sous pseudonymes');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('015' ,'Bibliographies d''ouvrages sur des lieux précis');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('016' ,'Bibliographies d''ouvrages sur des sujets précis');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('017' ,'Catalogues de sujets généraux');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('018' ,'Catalogues classés par auteurs, dates, etc.');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('019' ,'Catalogues de dictionnaires');

INSERT INTO THEME (noTheme,intituleTheme) VALUES ('020' ,'Bibliothéconomie et Science de l''information');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('021' ,'Relation des bibliothèques (avec les archives, les centres d''information, etc.)');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('022' ,'Administration d''installations physiques');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('023' ,'Gestion des ressources humaines');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('024' ,'(Vacant)');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('025' ,'Gestion des bibliothèques');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('026' ,'Bibliothèques de sujets précis');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('027' ,'Bibliothèques générales');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('028' ,'Lecture et utilisation des autres médias d''information');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('029' ,'(Vacant)');

INSERT INTO THEME (noTheme,intituleTheme) VALUES ('030' ,'Encyclopédies générales');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('031' ,'Encyclopédies en anglais américain');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('032' ,'Encyclopédies en anglais');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('033' ,'Encyclopédies dans d''autres langues germaniques');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('034' ,'Encyclopédies en français, occitan, et catalan');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('035' ,'Encyclopédies en italien, roumain, et langues apparentées');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('036' ,'Encyclopédies en espagnol et portugais');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('037' ,'Encyclopédies en langues slaves');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('038' ,'Encyclopédies en langues scandinaves');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('039' ,'Encyclopédies dans d''autres langues');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('040' ,'(Vacant)');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('050' ,'Publications en série d’ordre général');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('051' ,'Publications en série en anglais américain');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('052' ,'Publications en série en anglais');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('053' ,'Publications en série dans d''autres langues germaniques');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('054' ,'Publications en série en français, occitan, et catalan');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('055' ,'Publications en série en italien, roumain, et langues apparentées');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('056' ,'Publications en série en espagnol et portugais');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('057' ,'Publications en série en langues slaves');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('058' ,'Publications en série en langues scandinaves');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('059' ,'Publications en série dans d''autres langues');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('060' ,'Organisations générales et muséologie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('061' ,'Organisations en Amérique du Nord');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('062' ,'Organisations dans les îles Britanniques, en Angleterre');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('063' ,'Organisations en Europe centrale, en Allemagne');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('064' ,'Organisations en France et à Monaco');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('065' ,'Organisations en Italie et dans les îles voisines');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('066' ,'Organisations en péninsule Ibérique et dans les îles voisines');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('067' ,'Organisations en Europe de l''Est, en Russie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('068' ,'Organisations dans d''autres zones géographiques');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('069' ,'Muséologie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('070' ,'Médias documentaires, journalisme, édition');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('071' ,'Journaux en Amérique du Nord');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('072' ,'Journaux dans les îles Britanniques, en Angleterre');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('073' ,'Journaux en Europe centrale, en Allemagne');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('074' ,'Journaux en France et à Monaco');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('075' ,'Journaux en Italie et dans les îles voisines');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('076' ,'Journaux en péninsule Ibérique et dans les îles voisines');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('077' ,'Journaux en Europe de l''Est, en Russie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('078' ,'Journaux en Scandinavie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('079' ,'Journaux dans d''autres zones géographiques');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('080' ,'Recueils généraux');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('081' ,'Recueils en anglais américain');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('082' ,'Recueils en anglais');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('083' ,'Recueils dans d''autres langues germaniques');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('084' ,'Recueils en français, occitan, et catalan');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('085' ,'Recueils en italien, roumain, et langues apparentées');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('086' ,'Recueils en espagnol et portugais');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('087' ,'Recueils en langues slaves');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('088' ,'Recueils en langues scandinaves');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('089' ,'Recueils dans d''autres langues');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('090' ,'Manuscrits, livres rares, autres documents imprimés rares');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('091' ,'Manuscrits');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('092' ,'Tabellaires');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('093' ,'Incunables');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('094' ,'Livres imprimés');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('095' ,'Livres remarquables pour leur reliure');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('096' ,'Livres remarquables pour leurs illustrations');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('097' ,'Livres remarquables pour leur propriété ou leur origine');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('098' ,'Œuvres interdites, forgeries, canulars');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('099' ,'Livres remarquables pour leur format');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('100' ,'Philosophie et psychologie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('101' ,'Théorie de la philosophie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('102' ,'Divers');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('103' ,'Dictionnaires et encyclopédies');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('104' ,'(Vacant)');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('105' ,'Publications en série');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('106' ,'Organisations et gestion');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('107' ,'Education, recherche, sujets relatifs à la philosophie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('108' ,'Groupes de philosophes');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('109' ,'Histoire et biographie recueillie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('110' ,'Métaphysique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('111' ,'Ontologie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('112' ,'(Vacant)—auparavant Méthodologie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('113' ,'Cosmologie (Philosophie de la nature)');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('114' ,'Espace');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('115' ,'Temps');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('116' ,'Changement');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('117' ,'Structure');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('118' ,'Force et énergie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('119' ,'Nombre et quantité');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('120' ,'Épistémologie, causalité, genre humain');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('121' ,'Épistémologie (Science du savoir)');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('122' ,'Causalité');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('123' ,'Déterminisme et Indéterminisme');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('124' ,'Téléologie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('125' ,'(Vacant)—auparavant Infini');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('126' ,'L''individu');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('127' ,'L''inconscient et le subconscient');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('128' ,'Humanité');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('129' ,'Origine et devenir des âmes des individus');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('130' ,'Parapsychologie et occultisme');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('131' ,'Méthodes parapsychologiques et occultes pour atteindre le bien-être, le bonheur, la réussite');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('132' ,'(Vacant)—auparavant Troubles psychiques');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('133' ,'Sujets spécifiques de parapsychologie et d''occultisme');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('134' ,'(Vacant)—auparavant Mesmérisme et Clairvoyance');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('135' ,'Rêves et mystères');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('136' ,'(Vacant)—auparavant Caractéristiques mentales');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('137' ,'Graphologie divinatoire');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('138' ,'Physiognomonie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('139' ,'Phrénologie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('140' ,'Les divers points de vue et écoles philosophiques');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('141' ,'Idéalisme, systèmes et doctrines apparentées');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('142' ,'Criticisme');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('143' ,'Bergsonisme et intuitionnisme');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('144' ,'Humanisme, systèmes et doctrines apparentées');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('145' ,'Sensationnalisme');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('146' ,'Naturalisme, systèmes et doctrines apparentées');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('147' ,'Panthéisme, systèmes et doctrines apparentées');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('148' ,'Dogmatisme, éclectisme, libéralisme, syncrétisme, et traditionalisme');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('149' ,'Autres systèmes et doctrines philosophiques');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('150' ,'Psychologie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('151' ,'(Vacant)—auparavant Intellect');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('152' ,'Perception sensorielle, mouvement, émotions, et pulsions physiologiques');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('153' ,'Processus mentaux conscients et intelligence');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('154' ,'Subconscient, altered state et processus alternatifs');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('155' ,'Psychologie différentielle et psychologie du développement');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('156' ,'Psychologie comparée');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('157' ,'(Vacant)—auparavant Émotions');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('158' ,'Psychologie appliquée');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('159' ,'(Vacant)—auparavant Volonté');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('160' ,'Logique philosophique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('161' ,'Raisonnement inductif');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('162' ,'Raisonnement déductif');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('165' ,'Raisonnement fallacieux et sources d''erreur');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('166' ,'Syllogismes');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('167' ,'Hypothèses');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('168' ,'Argumentation et persuasion');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('169' ,'Analogie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('170' ,'Éthique (Philosophie morale)');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('171' ,'Systèmes éthiques');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('172' ,'Éthique politique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('173' ,'Éthique des relations familiales');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('174' ,'Éthique professionnelle');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('175' ,'Éthique du loisir, du temps libre, du spectacle, de la communication');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('176' ,'Éthique du sexe et de la reproduction');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('177' ,'Éthique des rapports sociaux');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('178' ,'Éthique de la consommation');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('179' ,'Autres normes d''éthiques');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('180' ,'Philosophie antique, médiévale, orientale');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('181' ,'Philosophie orientale');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('182' ,'Philosophie présocratique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('183' ,'Sophistique, socratique, autres philosophies liées au monde grec antique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('184' ,'Platonisme');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('185' ,'Aristotélisme');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('186' ,'Scepticisme et néoplatonisme');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('187' ,'Épicurisme');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('188' ,'Stoïcisme');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('189' ,'Philosophie médiévale occidentale');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('190' ,'Philosophie occidentale contemporaine et autres philosophies non orientales');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('191' ,'Philosophie américaine et canadienne');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('192' ,'Philosophies des îles britanniques');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('193' ,'Philosophie d''Allemagne et d''Autriche');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('194' ,'Philosophie de France');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('195' ,'Philosophie d''Italie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('196' ,'Philosophie d''Espagne et du Portugal');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('197' ,'Philosophie de Russie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('198' ,'Philosophie de Scandinavie et de Finlande');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('199' ,'Philosophie d''autres régions du monde');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('200' ,'Religion');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('201' ,'Mythologie religieuse, grandes catégories de religions, attitudes et relations entre les religions, théologie sociale');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('202' ,'Doctrines');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('203' ,'Culte public et autres pratiques');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('204' ,'Expérience, vie, pratique religieuses');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('205' ,'Morale religieuse');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('206' ,'Chefs spirituels et organisation');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('207' ,'Missions et enseignement religieux');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('208' ,'Sources');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('209' ,'Sectes et mouvements réformistes');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('210' ,'Philosophie et théorie de la religion');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('211' ,'Concepts de Dieu');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('212' ,'Existence de Dieu, moyens de connaître Dieu, attributs de Dieu');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('213' ,'Création');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('214' ,'Théodicée');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('215' ,'Science et religion');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('216' ,'[Vacant]');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('217' ,'[Vacant]');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('218' ,'Humanité (le genre humain)');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('219' ,'[Vacant]');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('220' ,'Bible');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('221' ,'Ancien Testament (Tanakh)');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('222' ,'Livres historiques de l''Ancien Testament');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('223' ,'Livres poétiques de l''Ancien Testament');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('224' ,'Livres prophétiques de l''Ancien Testament');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('225' ,'Nouveau Testament');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('226' ,'Évangiles et Actes des Apôtres');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('227' ,'Épitres');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('228' ,'Apocalypse de saint Jean');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('229' ,'Livres apocryphes et pseudépigraphes');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('230' ,'Christianisme Théologie chrétienne');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('231' ,'Dieu');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('232' ,'Jésus de Nazareth et sa famille Christologie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('233' ,'Humanité (le genre humain)');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('234' ,'Salut et grâce');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('235' ,'Êtres spirituels');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('236' ,'Eschatologie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('237' ,'[Vacant]');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('238' ,'Croyances, confessions de foi');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('239' ,'Apologétique et polémique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('240' ,'Théologie morale et spirituelle chrétiennes');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('241' ,'Morale chrétienne');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('242' ,'Textes de dévotion');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('243' ,'Textes d''évangélisation à l''intention des individus et des familles');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('244' ,'[Vacant]');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('245' ,'[Vacant]');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('246' ,'Art dans le christianisme');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('247' ,'Mobilier d''église et objets religieux');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('248' ,'Expérience, pratique, vie chrétiennes');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('249' ,'Pratiques chrétiennes dans la vie familiale');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('250' ,'Églises chrétiennes locales et ordres religieux chrétiens');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('251' ,'Prédication (homilétique)');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('252' ,'Textes de sermons (homélies)');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('253' ,'Fonctions et devoirs pastoraux (théologie pastorale)');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('254' ,'Administration des paroisses');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('255' ,'Congrégations et ordres religieux');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('256' ,'[Vacant]');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('257' ,'[Vacant]');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('258' ,'[Vacant]');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('259' ,'Activités pastorales auprès des familles, des catégories particulières de personnes');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('260' ,'Théologie chrétienne et société et ecclésiologie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('261' ,'Théologie chrétienne et société et relations et attitudes du christianisme envers les autres religions');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('262' ,'Ecclésiologie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('263' ,'Jours, temps, lieux destinés au culte');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('264' ,'Culte public');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('265' ,'Sacrements, autres rites et cérémonies');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('266' ,'Missions');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('267' ,'Associations à but religieux');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('268' ,'Enseignement religieux');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('269' ,'Renouveau spirituel');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('270' ,'Histoire et géographie du christianisme et de l''Église');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('271' ,'Congrégations et ordres religieux dans l''histoire de l''Église');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('272' ,'Persécutions');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('273' ,'Controverses et hérésies doctrinales');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('274' ,'Christianisme en Europe, Église chrétienne en Europe');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('275' ,'Christianisme en Asie, Église chrétienne en Asie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('276' ,'Christianisme en Afrique, Église chrétienne en Afrique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('277' ,'Christianisme en Amérique du Nord, Église chrétienne en Amérique du Nord');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('278' ,'Christianisme en Amérique du Sud, Église chrétienne en Amérique du Sud');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('279' ,'Christianisme dans les autres parties du monde, Église chrétienne dans les autres parties du monde');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('280' ,'Confessions et sectes de l''Église chrétienne');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('281' ,'Église primitive et Églises orientales');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('282' ,'Église catholique romaine');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('283' ,'Églises anglicanes');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('284' ,'Confessions protestantes d''origine européenne continentale et groupes connexes');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('285' ,'Églises presbytériennes, Églises réformées en Amérique, Églises congrégationalistes, puritanisme');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('286' ,'Églises baptistes, des disciples du Christ, adventistes');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('287' ,'Églises méthodistes, Églises liées au méthodisme');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('288' ,'[Vacant]');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('289' ,'Autres confessions et sectes');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('290' ,'Autres religions');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('291' ,'[Vacant]');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('292' ,'Religion classique (religions grecque et romaine)');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('293' ,'Religion germanique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('294' ,'Religions d''origine hindoue');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('295' ,'Zoroastrisme (mazdéisme, parsisme)');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('296' ,'Judaïsme');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('297' ,'Islam, Babisme et Bahaïsme');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('298' ,'[Vacant]');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('299' ,'Autres religions');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('300' ,'Sciences sociales');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('301' ,'Sociologie et anthropologie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('302' ,'Interaction sociale');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('303' ,'Processus sociaux');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('304' ,'Facteurs influençant le comportement social');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('305' ,'Groupes sociaux');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('306' ,'Culture et institutions');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('307' ,'Communautés');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('308' ,'[Vacant]');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('309' ,'[Vacant]');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('310' ,'Recueils de statistiques générales');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('311' ,'[Vacant]');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('312' ,'[Vacant]');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('313' ,'[Vacant]');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('314' ,'Statistiques générales de l''Europe');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('315' ,'Statistiques générales de l''Asie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('316' ,'Statistiques générales de l''Afrique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('317' ,'Statistiques générales de l''Amérique du Nord');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('318' ,'Statistiques générales de l''Amérique du Sud');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('319' ,'Statistiques générales des autres parties du monde');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('320' ,'Science politique (politique et gouvernement)');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('321' ,'Types d''États et de gouvernements');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('322' ,'Relations entre l''État et les groupes sociaux organisés');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('323' ,'Droits civils et politiques');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('324' ,'La vie politique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('325' ,'Migrations internationales et colonisation');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('326' ,'Esclavage et émancipation des esclaves');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('327' ,'Relations internationales');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('328' ,'Le processus législatif');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('329' ,'vacant');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('330' ,'Économie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('331' ,'Économie du travail');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('332' ,'Économie financière');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('333' ,'Économie de la terre et des ressources naturelles');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('334' ,'Coopératives');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('335' ,'Socialisme et systèmes apparentés');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('336' ,'Finances publiques');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('337' ,'Économie internationale');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('338' ,'Production');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('339' ,'Macroéconomie et sujets connexes');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('340' ,'Droit');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('341' ,'Droit international');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('342' ,'Droit constitutionnel et administratif');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('343' ,'Droit de la défense, droit fiscal, commercial, industriel');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('344' ,'Droit social, du travail, de la santé, de l''éducation et de la culture');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('345' ,'Droit pénal');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('346' ,'Droit privé');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('347' ,'Procédure civile et tribunaux');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('348' ,'Lois, réglementations, jurisprudence');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('349' ,'Droit interne des différents États. Ouvrages d''ensemble sur le droit de chaque pays');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('350' ,'Administration publique. Art et science militaire');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('351' ,'Administration publique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('352' ,'Généralités');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('353' ,'Secteurs spécifiques de l''administration');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('354' ,'Ministères et services chargés de l''environnement, des ressources naturelles, des affaires économiques');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('355' ,'Art et science militaires');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('356' ,'Infanterie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('357' ,'Forces montées');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('358' ,'Artillerie. Forces aériennes et spatiales');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('359' ,'Marine militaire');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('360' ,'Problèmes et services sociaux. Associations');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('361' ,'Problèmes sociaux. Aide sociale');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('362' ,'Problèmes et services d''aide sociale');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('363' ,'Autres problèmes et services sociaux');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('364' ,'Criminologie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('365' ,'Établissements pénitentiaires');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('366' ,'Associations');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('367' ,'Clubs');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('368' ,'Assurances');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('369' ,'Associations diverses');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('370' ,'Éducation, enseignement');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('371' ,'Les écoles et leurs activités, enseignement spécialisé, éducation spécialisée');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('372' ,'L''école élémentaire');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('373' ,'Enseignement secondaire');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('374' ,'Formation des adultes');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('375' ,'Programme d''enseignement');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('378' ,'Enseignement supérieur');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('379' ,'L''enseignement et l''État. Politique éducative');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('380' ,'Commerce, communications, transports');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('381' ,'Commerce intérieur');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('382' ,'Commerce international (commerce extérieur)');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('383' ,'Postes');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('384' ,'Communications, télécommunications');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('385' ,'Transports ferroviaires');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('386' ,'Transports par voies d''eau intérieures (Transport fluvial)');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('387' ,'Transports maritime, aérien, spatial');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('388' ,'Transports terrestre.Transports routiers');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('389' ,'Métrologie et normalisation');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('390' ,'Coutumes, savoir-vivre, folklore');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('391' ,'Costume et apparence personnelle');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('392' ,'Coutumes liées au cycle de l''existence et à la vie quotidienne');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('393' ,'Coutumes funéraires');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('394' ,'Coutumes générales');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('395' ,'Étiquette, savoir-vivre');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('396' ,'[Vacant]');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('397' ,'[Vacant]');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('398' ,'Folklore');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('399' ,'Coutumes de la guerre et de la diplomatie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('400' ,'Langage');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('401' ,'Philosophie et théorie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('402' ,'Ouvrages divers');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('403' ,'Dictionnaires, encyclopédies, concordances');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('404' ,'Sujets particuliers');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('405' ,'Publications en série');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('406' ,'Organisations');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('407' ,'Enseignement, recherche et sujets connexes');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('408' ,'Le langage chez les différents groupes');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('409' ,'Traitement géographique et biographique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('410' ,'Linguistique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('411' ,'Systèmes d''écriture des formes standard des langues');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('412' ,'Étymologie des formes standard des langues');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('413' ,'Dictionnaires des formes standard des langues');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('414' ,'Phonologie et phonétique des formes standard des langues');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('415' ,'Grammaire et syntaxe des formes standard des langues');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('416' ,'[Vacant]');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('417' ,'Dialectologie. Linguistique historique (diachronique)');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('418' ,'Standard usage (Prescriptive linguistics)');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('419' ,'Langage structuré autre que le langage parlé et le langage écrit');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('420' ,'Anglais et vieil anglais (anglo-saxon)');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('421' ,'Écriture et phonologie de l''anglais standard');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('422' ,'Étymologie de l''anglais');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('423' ,'Dictionnaires d''anglais');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('424' ,'[Vacant]');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('425' ,'Grammaire de l''anglais standard');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('426' ,'[Vacant]');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('427' ,'Variantes historiques et géographiques, variantes locales');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('428' ,'Usage');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('429' ,'Vieil anglais');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('430' ,'Langues germaniques. Allemand');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('431' ,'Écriture et phonologie de l''allemand standard');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('432' ,'Étymologie de l''allemand');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('433' ,'Dictionnaires d''allemand');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('434' ,'[Vacant]');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('435' ,'Grammaire de l''allemand standard');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('436' ,'[Vacant]');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('437' ,'Variantes historiques et géographiques, variantes locales');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('438' ,'Usage');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('439' ,'Autres langages germaniques');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('440' ,'Langues romanes. Français');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('441' ,'Écriture et phonologie du français standard');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('442' ,'Étymologie du français');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('443' ,'Dictionnaires de français');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('444' ,'[Vacant]');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('445' ,'Grammaire français');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('446' ,'[Vacant]');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('447' ,'Variantes historiques et géographiques, variantes locales');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('448' ,'Usage');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('449' ,'Occitan Catalan, Franco-Provençal');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('450' ,'Italien, sarde, dalmate, roumain, langues rhéto-romanes');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('451' ,'Écriture et phonologie de l''italien standard');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('452' ,'Étymologie l''italien standard');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('453' ,'Dictionnaires d''italien');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('454' ,'[Vacant]');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('455' ,'Grammaire de l''italien standard');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('456' ,'[Vacant]');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('457' ,'Variantes historiques et géographiques, variantes locales');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('458' ,'Usage');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('459' ,'Roumain et langues rhéto-romanes');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('460' ,'Langues espagnole et portugaise');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('461' ,'Écriture et phonologie de l''espagnol standard');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('462' ,'Étymologie l''espagnol standard');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('463' ,'Dictionnaires d''espagnol');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('464' ,'[Vacant]');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('465' ,'Grammaire de l''espagnol standard');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('466' ,'[Vacant]');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('467' ,'Variantes historiques et géographiques, variantes locales');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('468' ,'Usage');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('469' ,'Langue portugaise');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('470' ,'Langues italiques. Latin');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('471' ,'Écriture et phonologie du latin classique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('472' ,'Étymologie du latin classique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('473' ,'Dictionnaires de latin');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('474' ,'[Vacant]');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('475' ,'Grammaire de latin classique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('476' ,'[Vacant]');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('477' ,'Latin archaïque, post-classique, populaire');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('478' ,'Usage du latin classique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('479' ,'autres langues italiques');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('480' ,'Langues helléniques. Grec classique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('481' ,'Écriture et phonologie du grec classique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('482' ,'Étymologie du grec classique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('483' ,'Dictionnaires de grec classique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('484' ,'[Vacant]');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('485' ,'Grammaire du grec classique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('486' ,'[Vacant]');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('487' ,'Grec post-classique, hellénistique et byzantin');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('488' ,'Usage du grec classique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('489' ,'Autres langues helléniques');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('490' ,'Autres langues');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('491' ,'Langues indo-européennes orientales et langues cetiques');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('492' ,'Langues afro-asiatiques (chamito-sémitiques)');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('493' ,'Langues afro-asiatiques non chamitiques');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('494' ,'Langues ouralo-altaïques, hyperboréennes (paléo-sibériennes) et dravidiennes');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('495' ,'Langues de l''Asie de l''Est et du Sud-Est. Langues sino-tibétaines');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('496' ,'Langues africaines');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('497' ,'Langues indiennes et autochtones de l''Amérique du Nord');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('498' ,'Langues indiennes de l''Amérique du Sud');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('499' ,'Langues papoues de l''Océanie, langues malayo-polynésiennes, diverses autres langues');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('500' ,'Sciences de la nature et mathématiques');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('501' ,'Philosophie et théorie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('502' ,'Ouvrages divers');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('503' ,'Dictionnaires, encyclopédies, tableaux comparatifs');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('504' ,'[Vacant]');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('505' ,'Publications en série');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('506' ,'Organisations');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('507' ,'Étude et enseignement');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('508' ,'Histoire naturelle');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('509' ,'Étude historique, géographique, relative à des personnes');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('510' ,'Mathématiques');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('511' ,'Principes généraux des mathématiques');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('512' ,'Algèbre, théorie des nombres');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('513' ,'Arithmétique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('514' ,'Topologie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('515' ,'Analyse');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('516' ,'Géométrie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('517' ,'[Vacant]');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('518' ,'[Vacant]');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('519' ,'Probabilités et mathématiques appliquées');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('520' ,'Astronomie et sciences connexes');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('521' ,'Mécanique céleste');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('522' ,'Techniques, équipements, matériels');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('523' ,'Astronomie descriptive');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('524' ,'[Vacant]');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('525' ,'Terre (géographie astronomique)');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('526' ,'Géographie mathématique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('527' ,'Navigation astronomique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('528' ,'Éphémérides');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('529' ,'Chronologie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('530' ,'Physique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('531' ,'Mécanique classique, Mécanique des solides');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('532' ,'Mécanique des fluides, Mécanique des liquides');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('533' ,'Mécanique des gaz');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('534' ,'Son et vibrations associées, Acoustique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('535' ,'Lumière et phénomènes de l''infrarouge et de l''ultraviolet');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('536' ,'Chaleur');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('537' ,'Électricité et électronique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('538' ,'Magnétisme');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('539' ,'Physique moderne');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('540' ,'Chimie et sciences connexes');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('541' ,'Chimie physique et théorique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('542' ,'Techniques, procédés, appareils, équipement, matériel');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('543' ,'Chimie analytique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('544' ,'Analyse qualitative');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('545' ,'Analyse quantitative');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('546' ,'Chimie minérale');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('547' ,'Chimie organique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('548' ,'Cristallographie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('549' ,'Minéralogie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('550' ,'Sciences de la Terre');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('551' ,'Géologie, météorologie, hydrologie générale');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('552' ,'Pétrologie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('553' ,'Géologie économique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('554' ,'Géologie de l''Europe');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('555' ,'Géologie de l''Asie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('556' ,'Géologie de l''Afrique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('557' ,'Géologie de l''Amérique du Nord');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('558' ,'Géologie de l''Amérique du Sud');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('559' ,'Géologie des autres parties du monde');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('560' ,'Paléontologie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('561' ,'Paléobotanique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('562' ,'Invertébrés fossiles');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('563' ,'Fossiles marins et des bords de mers');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('564' ,'Mollusques et molluscoïdes fossiles');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('565' ,'Arthropodes fossiles');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('566' ,'Cordés fossiles');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('567' ,'Vertébrés à sang froid fossiles. Poissons fossiles');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('568' ,'Oiseaux fossiles');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('569' ,'Mammifères fossiles');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('570' ,'Sciences de la vie. Biologie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('571' ,'Physiologie et sujets voisins');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('572' ,'Biochimie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('573' ,'Anatomie, histologie et physiologie animales');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('574' ,'[Vacant]');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('575' ,'Anatomie et physiologie végétales');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('576' ,'Génétique et évolution');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('577' ,'Écologie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('578' ,'Histoire naturelle des organismes et sujets apparenté');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('579' ,'Micro-organismes, champignons, algues');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('580' ,'Plantes');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('581' ,'Sujets spécifiques de la biologie végétale');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('582' ,'Plantes étudiées en fonction de leurs propriétés végétatives particulières et de leurs fleurs');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('583' ,'Magnoliopsidées (Dicotylédones)');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('584' ,'Liliopsidées (Monocotylédones)');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('585' ,'Pinophytes (Gymnospermes), Coniférales (Conifères)');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('586' ,'Cryptogames (plantes sans graine)');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('587' ,'Ptéridophytes (plantes vasculaires sans graines, fougères)');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('588' ,'Bryophytes (mousses)');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('589' ,'Vacant — précédemment foresterie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('590' ,'Animaux');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('591' ,'Sujets particuliers de la biologie animale');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('592' ,'Invertébrés');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('593' ,'Divers invertébrés marins et du littoral');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('594' ,'Mollusques et molluscoïdes');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('595' ,'Arthropodes');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('596' ,'Chordés. Vertébrés');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('597' ,'Vertébrés à sang froid. Poissons');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('598' ,'Oiseaux');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('599' ,'Mammifères');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('600' ,'Technologie (Sciences appliquées)');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('601' ,'Philosophie et théorie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('602' ,'Ouvrages divers');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('603' ,'Dictionnaires, encyclopédies, ouvrages comparatifs');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('604' ,'Dessin industriel. Technique des substances dangereuses');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('605' ,'Publications en séries. Périodiques');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('606' ,'Organisations');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('607' ,'Enseignement, recherche');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('608' ,'Inventions et brevets');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('609' ,'Histoire et géographie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('610' ,'Sciences médicales. Médecine');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('610.3' ,'Dictionnaires, encyclopédies');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('610.6' ,'Organisations, gestion, professions médicales');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('610.7' ,'Étude et enseignement, recherche, soins infirmiers, sujets connexes');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('610.72' ,'Recherche médicale');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('610.9' ,'Histoire et géographie de la médecine');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('611' ,'Anatomie humaine, biologie des tissus, cytologie humaine');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('611.1' ,'Appareil cardio-vasculaire');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('611.2' ,'Appareil respiratoire');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('611.3' ,'Appareil digestif');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('611.4' ,'Système lymphatique et glandulaire');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('611.6' ,'Appareil génito-urinaire');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('611.7' ,'Organes moteurs et tégumentaires');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('611.8' ,'Système nerveux et organes des sens');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('611.81' ,'Cerveau');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('611.84' ,'Yeux');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('611.85' ,'Oreilles');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('611.9' ,'Anatomie topographique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('612' ,'Physiologie humaine');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('613' ,'Promotion de la santé');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('613.1' ,'Rôle de l''environnement naturel');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('613.2' ,'Diététique : aliments et boissons. Valeurs nutritives des aliments');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('613.4' ,'Propreté personnelle. Soins de la personne');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('613.5' ,'Rôle de l''environnement non naturel');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('613.6' ,'Sujets spéciaux');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('613.62' ,'Hygiène industrielle');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('613.66' ,'Autodéfense');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('613.7' ,'Condition physique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('613.71' ,'Exercice et activités physiques');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('613.79' ,'Relaxation, repos, sommeil');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('613.8' ,'Toxicomanies');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('613.9' ,'Contrôle des naissances. Hygiène sexuelle. Procréation médicalement assistée');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('614' ,'Santé publique et sujets connexes');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('615' ,'Pharmacologie et thérapeutique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('616' ,'Maladies');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('617' ,'Chirurgie et sujets connexes');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('618' ,'Autres branches de la médecine. Gynécologie et obstétrique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('619' ,'Médecine expérimentale');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('620' ,'Art de l’ingénieur et activités connexes');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('621' ,'Physique appliquée');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('622' ,'Génie minier et activités connexes');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('623' ,'Génie militaire et naval');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('624' ,'Génie civil');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('625' ,'Chemins de fer, routes, autoroutes');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('626' ,'[Vacant]');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('627' ,'Génie hydraulique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('628' ,'Technique sanitaire et municipale. Génie Urbain');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('629' ,'Autres branches de l''art de l''ingénieur');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('630' ,'Agronomie, agriculture et activités connexes');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('631' ,'Techniques spécifiques, équipement');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('632' ,'Dégâts causés aux plantes, maladies et parasites');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('633' ,'Champs et cultures');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('634' ,'Vergers, fruits, foresterie. Arboriculture');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('635' ,'Produits des jardins (Horticulture). Légumes');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('636' ,'Élevage');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('637' ,'Industrie laitière');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('638' ,'Élevage d''insects');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('639' ,'Chasse et pêche commerciale, protection de la faune et de la flore');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('640' ,'Économie domestique (arts ménagers). Vie familiale');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('641' ,'Nourriture et boisson');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('642' ,'Repas, service à table');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('643' ,'Logement et équipement ménager');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('644' ,'Chauffage et autres équipements');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('645' ,'Mobilier et décoration');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('646' ,'Couture, Vêtement, gestion de la vie personnelle et familiale');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('647' ,'Organisation des établissements hôteliers, hôtels, restaurants');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('648' ,'Travaux d''entretien');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('649' ,'Puériculture ; soin à domicile des handicapés et des malades');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('650' ,'Gestion de l''entreprise et services auxiliaires');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('651' ,'Bureaux');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('652' ,'Procédés de la communication écrite');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('653' ,'Sténographie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('657' ,'Comptabilité');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('658' ,'Gestion des entreprises privées et publiques');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('659' ,'Publicité et relations publiques');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('660' ,'Génie chimique (chimie industrielle) et techniques connexes');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('661' ,'Technologie des produits chimiques industriels (chimie lourde)');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('662' ,'Technologie des explosifs, combustibles, produits dérivés');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('663' ,'Technologie des boissons');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('664' ,'Technologie des aliments');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('665' ,'Technologie industrielle relative aux huiles, graisses, cires et gaz industriels');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('666' ,'Technologie de la céramique et technologies annexes');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('667' ,'Nettoyage, industries des colorants');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('668' ,'Technologie des autres produits organiques');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('669' ,'Métallurgie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('670' ,'Fabrication industrielle');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('671' ,'Métallurgie industrielle');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('672' ,'Métallurgie des métaux ferreux');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('673' ,'Métallurgie des métaux non-ferreux');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('674' ,'Technologie du bois, produits du bois, liège');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('675' ,'Technologie du cuir et de la fourrure');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('676' ,'Technologie de la pâte à papier et du papier');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('677' ,'Textiles');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('678' ,'Élastomères & produits élastomères');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('679' ,'Autres produits faits de matériaux divers');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('680' ,'Fabrications de produits à usages particuliers');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('681' ,'Instruments de précision');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('682' ,'Ferronnerie, petits travaux de forge');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('683' ,'Quincaillerie, serrurerie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('684' ,'Ameublement, bricolage à la maison');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('685' ,'Articles de cuir et de fourrures, produits dérivés');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('686' ,'Imprimerie et activités dérivées');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('687' ,'Fabrication de vêtements');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('688' ,'Autres articles, technologie des emballages');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('689' ,'[Vacant]');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('690' ,'Bâtiments');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('691' ,'Matériaux de construction');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('692' ,'Techniques annexes');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('693' ,'Construction de bâtiments de matériaux déterminés et à des fins déterminées');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('694' ,'Utilisation du bois dans la construction, menuiserie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('695' ,'Couverture, toiture');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('696' ,'Plomberie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('697' ,'Ingénierie du Chauffage, ventilation et climatisation');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('698' ,'Finitions');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('699' ,'[Vacant]');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('700' ,'Les arts. Beaux-arts et arts décoratifs');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('701' ,'Philosophie et théorie des beaux-arts et des arts décoratifs');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('702' ,'Ouvrages divers sur les beaux-arts et des arts décoratifs');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('703' ,'Dictionnaires, encyclopédies des beaux-arts et des arts décoratifs');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('704' ,'Caractères particuliers');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('705' ,'Publications en série');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('706' ,'Organisations et commerce');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('707' ,'Étude et enseignement');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('708' ,'Galeries, musées, collections d''art');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('709' ,'Histoire et géographie des beaux-arts et des arts décoratifs');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('710' ,'Urbanisme. Art du paysage');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('711' ,'Aménagement du territoire (urbanisme)');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('712' ,'Arts du paysage');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('713' ,'Architecture du paysage des voies de communication');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('714' ,'Pièces d''eau dans l''architecture du paysage');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('715' ,'Plantes ligneuses dans l''architecture du paysage');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('716' ,'Plantes herbacées dans l''architecture du paysage');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('717' ,'Mobilier urbain');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('718' ,'Cimetières');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('719' ,'Sites naturels');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('720' ,'Architecture');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('721' ,'Construction architecturale');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('722' ,'Architecture de l''Antiquité et de l''Orient (jusqu''à 300)');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('723' ,'Architecture médiévale (300-1399)');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('724' ,'Architecture 1400-...');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('725' ,'Édifices d''usage public');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('726' ,'Édifices religieux');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('727' ,'Édifices destinés à l''éducation et la recherche');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('728' ,'Bâtiments d''habitation');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('729' ,'Décoration des édifices');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('730' ,'Arts plastiques. Sculpture');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('731' ,'Procédés et représentations');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('732' ,'Sculpture primitive et orientale, et de l''Occident ancien');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('733' ,'Sculpture grecque, étrusque, romaine');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('734' ,'Sculpture médiévale, 500-1400');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('735' ,'Sculpture moderne, 1400-...');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('736' ,'Taille, ciselage, sculpture');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('737' ,'Numismatique et sigillographie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('738' ,'Céramique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('739' ,'Art du métal');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('740' ,'Dessin, arts décoratifs');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('741' ,'Dessin et dessins');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('742' ,'Perspective');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('743' ,'Le dessin et les dessins, classés par sujets');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('744' ,'[vacant]');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('745' ,'Arts décoratifs, arts mineurs');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('746' ,'Art et artisanat des textiles');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('747' ,'Décoration d''intérieur');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('748' ,'Verre');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('749' ,'Mobiliers et accessoires');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('750' ,'La peinture et les peintures');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('751' ,'Procédés et types de peintures');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('752' ,'Couleur');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('753' ,'Sujets allégoriques, mythologiques, symboliques');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('754' ,'Scènes de la vie quotidienne');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('755' ,'Peinture religieuse');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('756' ,'[vacant]');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('757' ,'Représentations de la personne. Portraits');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('758' ,'Autres sujets');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('759' ,'Histoire et géographie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('760' ,'Arts graphiques. La gravures et les gravures');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('761' ,'Procédés en relief');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('762' ,'[vacant]');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('763' ,'Lithographie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('764' ,'Chromolithographie et sérigraphie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('765' ,'Gravure sur métal');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('766' ,'Manière noire, aquatinte');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('767' ,'Eau-forte et pointe sèche');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('768' ,'[vacant]');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('769' ,'Estampes');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('770' ,'Photographie et photographies');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('771' ,'Appareils, équipements, matériels');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('772' ,'Procédés utilisant des sels métalliques');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('773' ,'Procédés par pigments');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('774' ,'Holographie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('775' ,'[vacant]');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('776' ,'Art numérique. Art par ordinateur');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('777' ,'Cinématographie et Vidéographie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('778' ,'Différents domaines de la photographie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('779' ,'Photographies, recueils de photographies');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('780' ,'Musique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('781' ,'Principes généraux et formes musicales');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('782' ,'Musique vocale');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('783' ,'Musique pour voix seule. La voix');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('784' ,'Ensembles instrumentaux');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('785' ,'Ensembles à un seul instrument par partie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('786' ,'Claviers, instruments mécaniques et électriques, percussions');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('787' ,'Instruments à cordes');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('788' ,'Instruments à vent');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('789' ,'[vacant]');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('790' ,'Loisirs et arts du spectacle. Sports');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('791' ,'Représentations scéniques');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('792' ,'Théâtre. Représentations sur scène');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('793' ,'Jeux d''intérieur');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('794' ,'Jeux d''habileté d''intérieur');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('795' ,'Jeux de hasard. Jeux de cartes');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('796' ,'Sports, jeux athlétiques d''extérieur');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('797' ,'Sports nautiques et aériens');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('798' ,'Sports équestres, courses d''animaux');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('799' ,'Pêche, chasse, tir');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('800' ,'Littérature (Belles-lettres) et techniques d''écriture');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('801' ,'Philosophie et théorie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('802' ,'Ouvrages divers');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('803' ,'Dictionnaires, encyclopédies, concordances');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('804' ,'[Vacant]');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('805' ,'Publications en série');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('806' ,'Organisations');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('807' ,'Étude et enseignement');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('808' ,'Rhétorique et recueils');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('809' ,'Histoire, analyse, critiques littéraires générales');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('810' ,'Littérature américaine de langue anglaise');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('811' ,'Poésie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('812' ,'Littérature dramatique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('813' ,'Fiction');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('814' ,'Essais');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('815' ,'Discours');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('816' ,'Correspondance');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('817' ,'Humour, satire');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('818' ,'Textes divers');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('819' ,'[Vacant]');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('820' ,'Littératures anglaise et anglo-saxonne');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('821' ,'Poésie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('822' ,'Littérature dramatique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('823' ,'Fiction');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('824' ,'Essais');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('825' ,'Discours');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('826' ,'Correspondance');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('827' ,'Humour, satire');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('828' ,'Textes divers');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('829' ,'Anglo-saxon. Vieil anglais');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('830' ,'Littérature des langues germaniques. Littérature allemande');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('831' ,'Poésie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('832' ,'Littérature dramatique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('833' ,'Fiction');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('834' ,'Essais');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('835' ,'Discours');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('836' ,'Correspondance');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('837' ,'Humour, satire');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('838' ,'Textes divers');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('839' ,'Autres littératures germaniques');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('840' ,'Littérature des langues romanes. Littérature française');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('841' ,'Poésie de langue française');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('842' ,'Littérature dramatique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('843' ,'Fiction');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('843.01' ,'La nouvelle');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('843.06' ,'La bande dessinée');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('843.08' ,'les genres romanesques');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('843.08.081' ,'Le roman historique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('843.08.083' ,'Le roman social, psychhologique, réaliste');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('843.08.085' ,'Le roman sentimental');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('843.08.087.2',' Le roman à énigme, à suspense, le roman noir');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('843.08.087.6',' La science fiction');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('844' ,'Essais');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('845' ,'Discours');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('846' ,'Correspondance');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('847' ,'Humour, satire');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('848' ,'Écrits divers');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('849' ,'Littératures provençales et catalanes');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('850' ,'Littératures italienne, roumaine, rhéto-romane');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('851' ,'Poésie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('852' ,'Littérature dramatique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('853' ,'Fiction');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('854' ,'Essais');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('855' ,'Discours');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('856' ,'Correspondance');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('857' ,'Humour, satire');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('858' ,'Textes divers');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('859' ,'Roumain et rhéto-roman');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('860' ,'Littératures espagnole et portugaise');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('861' ,'Poésie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('862' ,'Littérature dramatique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('863' ,'Fiction');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('864' ,'Essais');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('865' ,'Discours');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('866' ,'Correspondance');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('867' ,'Humour, satire');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('868' ,'Textes divers');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('869' ,'Portugais et brésilien');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('870' ,'Littératures des langues italiques. Littérature latine');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('871' ,'Poésie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('872' ,'Littérature dramatique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('873' ,'Poésie épique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('874' ,'Poésie lyrique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('875' ,'Discours');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('876' ,'Correspondances');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('877' ,'Littérature satirique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('878' ,'Écrits divers');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('879' ,'Littératures d''autres langues italiques');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('880' ,'Littératures des langues helléniques. Littérature grecque classique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('881' ,'Poésie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('882' ,'Littérature dramatique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('883' ,'Poésie épique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('884' ,'Poésie lyrique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('885' ,'Discours');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('886' ,'Correspondances');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('887' ,'Littérature satirique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('888' ,'Divers écrits');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('889' ,'Littérature grecque moderne');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('890' ,'Littératures des autres langues');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('891' ,'Littératures indo-européennes du groupe oriental et littératures celtiques');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('892' ,'Littératures afro-asiatiques (chamito-sémitique)');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('893' ,'Littératures chamitique et tchadienne');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('894' ,'Littératures ouralo-altaïque, paléosibérienne, finno-ougriennes (hongroise, finnoise), dravidienne');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('895' ,'Littérature des pays d''Asie de l''Est et du Sud-Est');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('896' ,'Littératures africaines');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('897' ,'Littératures des langues indiennes et autochtones d''Amérique du Nord');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('898' ,'Littératures des langues indiennes et autochtones d''Amérique du Sud');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('899' ,'Littératures des langues non austronésiennes de l''Océanie, des langues austronésiennes, de diverses autres langues');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('899.3' ,'Littérature malgache');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('899.92' ,'Basque');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('899.992' ,'Espéranto');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('900' ,'Généralités sur la Géographie et l’Histoire');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('901' ,'Philosophie et théorie de l''histoire');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('902' ,'Ouvrages divers');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('903' ,'Dictionnaires, encyclopédies, concordances');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('904' ,'Recueils de récits d''événements');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('905' ,'Publications en série');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('906' ,'Organisations');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('907' ,'Enseignement et recherche');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('907.2' ,'Recherche, historiographie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('908' ,'Histoire des différents groupes de personnes');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('909' ,'Histoire du monde. Civilisation');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('910' ,'Géographie et voyages');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('910.2' ,'Ouvrages divers');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('910.3' ,'Dictionnaires, encyclopédies, concordances');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('910.4' ,'Récits de voyage');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('910.7' ,'Étude et enseignement. Recherche');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('910.9' ,'Traitement historique, géographie, biographique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('911' ,'Géographie historique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('912' ,'Représentations graphiques de la surface terrestre et des mondes extraterrestres');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('913' ,'Le monde ancien : géographie et voyages');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('914' ,'Géographie de l''Europe');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('915' ,'Géographie de l''Asie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('916' ,'Géographie de l''Afrique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('917' ,'Géographie de l''Amérique du Nord');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('918' ,'Géographie de l''Amérique du Sud');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('919' ,'Géographie des autres parties du monde et des mondes extra-terrestres');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('920' ,'Biographie, généalogie, emblèmes, insignes');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('921' ,'Philosophes et psychologues');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('922' ,'Chefs et penseurs religieux. Religieux');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('923' ,'Politiciens, économistes, juristes, enseignants');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('924' ,'Linguistes');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('925' ,'Savants');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('927' ,'Artistes. Sportifs');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('928' ,'Écrivains');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('929' ,'Généalogie, onomastique, emblèmes');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('930' ,'Histoire générale du monde ancien, jusqu''à 499 apr. J.-C.');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('931' ,'Chine jusqu''à 420 apr. J.-C.');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('932' ,'Égypte jusqu''à 640 apr. J.-C.');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('933' ,'Palestine jusqu''à 70 apr. J.-C.');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('934' ,'Inde jusqu''à 647 apr. J.-C.');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('935' ,'Mésopotamie et Plateau Iranien jusqu''à 637 apr. J.-C.');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('936' ,'Pays d''Europe sirués au nord et à l''ouest de la péninsule Italique jusqu''à 499 apr. J.-C.');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('937' ,'Péninsule Italique et territoires annexes jusqu''à 476 apr. J.-C.');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('938' ,'Grèce jusqu''à 323 apr. J.-C.');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('939' ,'Autres parties du monde ancien');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('940' ,'Histoire générale de l’Europe');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('941' ,'Iles britanniques');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('942' ,'Angleterre et Pays de Galles');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('943' ,'Europe centrale. Allemagne');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('944' ,'France & Monaco');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('945' ,'Italie, Saint-Marin, Vatican, Malte');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('946' ,'Péninsule Ibérique. Espagne');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('946.9' ,'Portugal');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('947' ,'Russie et pays d''Europe de l''Est');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('948' ,'Europe du Nord. Scandinavie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('949' ,'Autres pays d''Europe');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('950' ,'Histoire générale de l’Asie. Orient. Extrême-Orient');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('951' ,'Chine et territoires adjacents');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('952' ,'Japon et îles adjacentes');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('953' ,'Péninsule Arabique et territoires adjacents');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('954' ,'Asie du Sud. Inde');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('955' ,'Iran');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('956' ,'Moyen-Orient (Proche-Orient)');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('957' ,'Sibérie (Russie d''Asie)');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('958' ,'Asie centrale');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('959' ,'Asie du Sud-Est');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('960' ,'Histoire générale de l’Afrique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('961' ,'Tunisie et Libye');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('962' ,'Égypte et Soudan');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('963' ,'Éthiopie et Érythrée');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('964' ,'Maroc. Côtes du Nord-Ouest africain et îles au large');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('965' ,'Algérie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('966' ,'Afrique occidentale et îles au large');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('967' ,'Afrique centrale et îles au large');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('968' ,'Afrique du Sud');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('969' ,'Îles du sud de L''Océan Indien');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('970' ,'Histoire générale de l’Amérique du Nord');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('971' ,'Canada');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('972' ,'Amérique centrale. Mexique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('973' ,'États-Unis');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('980' ,'Histoire générale de l’Amérique du Sud');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('981' ,'Brésil');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('982' ,'Argentine');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('983' ,'Chili');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('984' ,'Bolivie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('985' ,'Pérou');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('986' ,'Nord-Ouest de l''Amérique du Sud');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('987' ,'Vénézuela');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('988' ,'Guyane');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('988.2' ,'Guyane française');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('989' ,'Paraguay & Uruguay');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('990' ,'Histoire générale des autres pays du monde. Océanie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('993' ,'Nouvelle-Zélande');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('994' ,'Australie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('995' ,'Nouvelle-Guinée. Mélanésie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('996' ,'Autres régions du Pacifique, Polynésie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('997' ,'Îles de l''Océan Atlantique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('998' ,'Îles de l''Arctique et de l’Antarctique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('999' ,'Mondes extra-terrestres');
spool off
set define on
commit;
/