INSERT INTO THEME (noTheme,intituleTheme) VALUES ('000' ,'Généralités sur l’informatique, l’information, ouvrages généraux');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('010' ,'Bibliographie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('020' ,'Bibliothéconomie et Science de l''information');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('030' ,'Encyclopédies générales');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('050' ,'Publications en série d’ordre général');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('060' ,'Organisations générales et muséologie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('070' ,'Médias documentaires, journalisme, édition');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('080' ,'Recueils généraux');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('090' ,'Manuscrits, livres rares, autres documents imprimés rares');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('100' ,'Philosophie et psychologie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('110' ,'Métaphysique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('120' ,'Épistémologie, causalité, genre humain');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('130' ,'Parapsychologie et occultisme');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('140' ,'Les divers points de vue et écoles philosophiques');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('150' ,'Psychologie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('160' ,'Logique philosophique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('170' ,'Éthique (Philosophie morale)');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('180' ,'Philosophie antique, médiévale, orientale');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('190' ,'Philosophie occidentale contemporaine et autres philosophies non orientales');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('200' ,'Religion');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('210' ,'Philosophie et théorie de la religion');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('220' ,'Bible');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('230' ,'Christianisme Théologie chrétienne');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('240' ,'Théologie morale et spirituelle chrétiennes');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('250' ,'Églises chrétiennes locales et ordres religieux chrétiens');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('260' ,'Théologie chrétienne et société et ecclésiologie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('270' ,'Histoire et géographie du christianisme et de l''Église');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('280' ,'Confessions et sectes de l''Église chrétienne');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('290' ,'Autres religions');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('300' ,'Sciences sociales');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('310' ,'Recueils de statistiques générales');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('320' ,'Science politique (politique et gouvernement)');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('330' ,'Économie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('340' ,'Droit');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('350' ,'Administration publique. Art et science militaire');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('360' ,'Problèmes et services sociaux. Associations');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('370' ,'Éducation, enseignement');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('380' ,'Commerce, communications, transports');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('390' ,'Coutumes, savoir-vivre, folklore');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('400' ,'Langage');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('410' ,'Linguistique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('420' ,'Anglais et vieil anglais (anglo-saxon)');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('430' ,'Langues germaniques. Allemand');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('440' ,'Langues romanes. Français');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('450' ,'Italien, sarde, dalmate, roumain, langues rhéto-romanes');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('460' ,'Langues espagnole et portugaise');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('470' ,'Langues italiques. Latin');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('480' ,'Langues helléniques. Grec classique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('490' ,'Autres langues');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('500' ,'Sciences de la nature et mathématiques');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('510' ,'Mathématiques');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('520' ,'Astronomie et sciences connexes');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('530' ,'Physique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('540' ,'Chimie et sciences connexes');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('550' ,'Sciences de la Terre');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('560' ,'Paléontologie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('570' ,'Sciences de la vie. Biologie');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('580' ,'Plantes');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('590' ,'Animaux');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('600' ,'Technologie (Sciences appliquées)');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('610' ,'Sciences médicales. Médecine');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('620' ,'Art de l’ingénieur et activités connexes');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('630' ,'Agronomie, agriculture et activités connexes');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('640' ,'Économie domestique (arts ménagers). Vie familiale');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('650' ,'Gestion de l''entreprise et services auxiliaires');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('660' ,'Génie chimique (chimie industrielle) et techniques connexes');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('670' ,'Fabrication industrielle');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('680' ,'Fabrications de produits à usages particuliers');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('690' ,'Bâtiments');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('700' ,'Les arts. Beaux-arts et arts décoratifs');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('710' ,'Urbanisme. Art du paysage');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('720' ,'Architecture');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('730' ,'Arts plastiques. Sculpture');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('740' ,'Dessin, arts décoratifs');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('750' ,'La peinture et les peintures');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('760' ,'Arts graphiques. La gravures et les gravures');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('770' ,'Photographie et photographies');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('780' ,'Musique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('790' ,'Loisirs et arts du spectacle. Sports');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('800' ,'Littérature (Belles-lettres) et techniques d''écriture');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('810' ,'Littérature américaine de langue anglaise');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('820' ,'Littératures anglaise et anglo-saxonne');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('830' ,'Littérature des langues germaniques. Littérature allemande');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('840' ,'Littérature des langues romanes. Littérature française');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('843.08.0872',' Le roman à énigme, à suspense, le roman noir');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('843.08.0876',' La science fiction');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('850' ,'Littératures italienne, roumaine, rhéto-romane');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('860' ,'Littératures espagnole et portugaise');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('870' ,'Littératures des langues italiques. Littérature latine');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('880' ,'Littératures des langues helléniques. Littérature grecque classique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('890' ,'Littératures des autres langues');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('900' ,'Généralités sur la Géographie et l’Histoire');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('910' ,'Géographie et voyages');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('920' ,'Biographie, généalogie, emblèmes, insignes');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('930' ,'Histoire générale du monde ancien, jusqu''à 499 apr. J.-C.');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('940' ,'Histoire générale de l’Europe');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('950' ,'Histoire générale de l’Asie. Orient. Extrême-Orient');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('960' ,'Histoire générale de l’Afrique');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('970' ,'Histoire générale de l’Amérique du Nord');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('980' ,'Histoire générale de l’Amérique du Sud');
INSERT INTO THEME (noTheme,intituleTheme) VALUES ('990' ,'Histoire générale des autres pays du monde. Océanie');
