SELECT ENAME,EMPNO FROM EMP EXCEPT SELECT E.ENAME,E.EMPNO FROM EMP E WHERE E.EMPNO IN (SELECT E2.MGR FROM EMP E2);
SELECT * FROM EMP WHERE MGR = (SELECT MGR FROM EMP WHERE ENAME = 'CLARK') AND NOT ENAME = 'CLARK';
SELECT * FROM EMP E1 WHERE EXISTS (SELECT * FROM EMP E2 WHERE ENAME = 'TURNER' AND E1.JOB = E2.JOB AND E1.MGR = E2.MGR);
SELECT ENAME,HIREDATE FROM EMP WHERE DEPTNO = (SELECT DEPTNO FROM DEPT WHERE DNAME = 'RESEARCH') AND HIREDATE IN (SELECT HIREDATE FROM EMP WHERE DEPTNO = (SELECT DEPTNO FROM DEPT WHERE DNAME = 'SALES'));
SELECT ENAME, TRUNC(SAL,-3) AS "Tranche de salaire" FROM EMP;
SELECT DECODE (DEPTNO, 10, '*****',ENAME),JOB,SAL,DEPTNO FROM EMP;
SELECT ENAME,JOB,LPAD('#',SAL/100,'#') AS "HISTORIGRAMME" FROM EMP ORDER BY SAL DESC;
SELECT ENAME,TRUNC(TO_DATE(HIREDATE,'DD-MON-YYYY'),'MON') FROM EMP;
SELECT ENAME, round(months_between(to_date ('01-JAN-2000','DD-MON-YYYY'), HIREDATE)) AS "Anciennete" FROM EMP;
